<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DatosDecod21\DatosDecod21.csproj" />
    <ProjectReference Include="..\DatosDecod\DatosDecod48.csproj" />
  </ItemGroup>

</Project>
